export function getParserSystemPrompt() {
  return [
    'You are a robust parser for receipts/invoices from noisy OCR text or images.',
    'Input can be highly variable: table, plain lines, mixed languages, partial cuts, low quality.',
    'Return ONLY valid JSON (no markdown, no extra keys).',
    'Do not hallucinate; when uncertain use null.',
    'Prioritize semantic correctness over cosmetic formatting.',
    'Treat totals/subtotals/tax/tip/discount lines as summary fields, not items.',
    'Numbers must be numeric (no symbols, no thousand separators).',
  ].join(' ');
}

export function getParserRulesPrompt() {
  return [
    'Return a JSON with this shape:',
    '{',
    '  "description": string|null,',
    '  "currency": string|null,',
    '  "date": "YYYY-MM-DD"|null,',
    '  "subtotal": number|null,',
    '  "taxAmount": number|null,',
    '  "tipAmount": number|null,',
    '  "totalAmount": number|null,',
    '  "taxIncludedInItems": boolean|null,',
    '  "items": [',
    '    { "name": string|null, "quantity": number|null, "unitPrice": number|null, "lineTotal": number|null }',
    '  ],',
    '  "notes": string|null',
    '}',
    '',
    'Parsing strategy:',
    '1) Detect line types first:',
    ' - ITEM lines: product/service entries.',
    ' - SUMMARY lines: subtotal, total, tax (VAT/IVA/IGV), tip/propina/service, discount/bonification.',
    ' - META lines: merchant, date, invoice/document number.',
    ' - Never output SUMMARY lines as items.',
    '',
    '2) Numeric normalization:',
    ' - Normalize decimal separators (1.234,56 -> 1234.56; 1,234.56 -> 1234.56).',
    ' - Strip currency symbols and thousand separators.',
    ' - Keep numeric precision to cents when possible.',
    '',
    '3) Item extraction (layout-agnostic):',
    ' - Support quantity before name, after name, or in separate column.',
    ' - Support unit price present or absent.',
    ' - Support line total present or absent.',
    " - Handle tabular tickets with headers like 'Articulo | Can | Total'.",
    ' - If a text line has no amount and the next line has amount/quantity, treat it as continuation of the same item name.',
    " - Example continuation: 'Gyozas Queso Pollo' + next line 'Curry' => item name 'Gyozas Queso Pollo Curry'.",
    " - Another example: 'Coca Cola zero x 400' + next line 'ml' => item name 'Coca Cola zero x 400 ml'.",
    " - Common patterns: '2 x 12.500', '2@12500', 'ITEM ... 2 12500 25000', '2 ITEM 25000'.",
    ' - If quantity and lineTotal exist but unitPrice missing, infer unitPrice = lineTotal / quantity when quantity > 0.',
    ' - If unitPrice and lineTotal exist but quantity missing, infer quantity only when near integer (tol 0.01).',
    ' - If only one amount is present on an item line, prefer lineTotal and leave other numeric fields null.',
    ' - If a row looks ambiguous between item and summary, prefer SUMMARY (avoid false item).',
    '',
    '4) Totals and taxes:',
    ' - subtotal: pre-tax, pre-tip amount when explicitly available.',
    ' - taxAmount: explicit VAT/IVA/IGV/tax line if present.',
    ' - tipAmount: explicit tip/gratuity/propina/service line.',
    ' - totalAmount must exclude tip when possible.',
    " - If you only find a 'grand total' that appears to include tip and tip is explicit, subtract tip.",
    ' - If tax is marked as included and no separate tax line exists, set taxIncludedInItems=true, else false if explicit tax line exists; otherwise null.',
    '',
    '5) Currency and date:',
    ' - Currency: return ISO code when clear (COP/USD/EUR/MXN/...) else null.',
    ' - Date: return YYYY-MM-DD when reliably parseable, else null.',
    '',
    '6) Reliability rules:',
    ' - Prefer explicit values over computed values.',
    ' - Do not force consistency by overwriting explicit totals.',
    ' - Put ambiguities/inferences in notes (short).',
    ' - If merchant name is the only clear text, use it as description; otherwise use a short receipt description.',
  ].join('\n');
}
